version: '3'


services:
  postgres:
    image: postgres:16-alpine
    user: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=postgres
    volumes:
      - ./database:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready" ]
        interval: 4s
        timeout: 5s
        retries: 5

  backend:
    build: .
    command: >
      sh -c "alembic upgrade head &&
             python -m src.proxy"
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres@postgres/postgres
    depends_on:
      postgres:
        condition: service_healthy
